export default {
	GET_CAR_INFO: "GET_CAR_INFO",
	GET_PEOPLE_INFO: "GET_PEOPLE_INFO",
	SET_PAGE_INDEX: "SET_PAGE_INDEX",

	CHANGE_HEADER: "CHANGE_HEADER",
	CHANGE_FOOTER: "CHANGE_FOOTER",

	GET_PROVINCE: "GET_PROVINCE",
	GET_CITY: "GET_CITY",
	GET_DISTRICT: "GET_DISTRICT",
	GET_VILLAGE: "GET_VILLAGE",

	// REVERSE_CARINFO: "REVERSE_CARINFO",
	// REVERSE_PEOPLEINFO: "REVERSE_PEOPLEINFO",

	SET_USERINFO: "SET_USERINFO",
	SET_MYPUBLISH: "SET_MYPUBLISH",

	SET_LOCATION: "SET_LOCATION",
	SET_USERINFO_PHONE: "SET_USERINFO_PHONE",
	SET_USER_AVATAR: "SET_USER_AVATAR", //头像显示
}
