export default {
	GET_CAR_INFO: "GET_CAR_INFO",
	GET_PEOPLE_INFO: "GET_PEOPLE_INFO",

	CHANGE_HEADER: "CHANGE_HEADER",
	CHANGE_FOOTER: "CHANGE_FOOTER",

	GET_PROVINCE: "GET_PROVINCE",
	GET_CITY: "GET_CITY",
	GET_DISTRICT: "GET_DISTRICT",
	GET_VILLAGE: "GET_VILLAGE"
}
