export default {
	CHANGE_HEADER:"CHANGE_HEADER",//改变页面header
	SET_STARTCITY:"SET_STARTCITY",//设置出发城市名
	SET_ENDCITY:"SET_ENDCITY",//设置到达城市
	SET_STARTDATE:"SET_STARTDATE",//设置开始出发时间
	SET_STARTCITYLIST:"SET_STARTCITYLIST",//设置出发城市的列表
	SET_ENDCITYLIST:"SET_ENDCITYLIST",//设置出发地址的列表,
	SET_RESULTLIST:"SET_RESULTLIST",//设置结果列表,
	SET_BUSINFO:"SET_BUSINFO",//设置乘坐车辆信息,提交订单所用
}